In [2]:
import pandas as pd

df = pd.read_csv("data/jeruk_balance_500.csv")
df

,diameter,berat,tebal_kulit,kadar_gula,asal_daerah,warna,musim_panen,kualitas
0,7.75,216.4,0.51,11.1,Kalimantan,oranye,kemarau,Bagus
1,7.43,237.9,0.43,10.6,Jawa Tengah,kuning,kemarau,Bagus
2,7.82,195.1,0.60,12.9,Jawa Barat,oranye,hujan,Bagus
3,8.26,184.9,0.49,13.9,Kalimantan,oranye,hujan,Bagus
4,7.38,182.2,0.42,10.6,Jawa Barat,oranye,kemarau,Bagus
...,...,...,...,...,...,...,...,...
495,6.06,106.0,0.73,7.7,Jawa Tengah,hijau,kemarau,Jelek
496,5.50,108.8,0.92,10.4,Jawa Barat,hijau,kemarau,Jelek
497,5.50,95.5,1.05,8.4,Jawa Barat,hijau,hujan,Jelek
498,7.69,221.8,0.70,13.0,Jawa Barat,oranye,hujan,Bagus
499,7.57,200.5,0.46,13.6,Kalimantan,oranye,hujan,Bagus

In [3]:
df.shape

(500, 8)

In [4]:
df.columns

Index(['diameter', 'berat', 'tebal_kulit', 'kadar_gula', 'asal_daerah',
       'warna', 'musim_panen', 'kualitas'],
      dtype='str')

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   diameter     500 non-null    float64
 1   berat        500 non-null    float64
 2   tebal_kulit  500 non-null    float64
 3   kadar_gula   500 non-null    float64
 4   asal_daerah  500 non-null    str
 5   warna        500 non-null    str
 6   musim_panen  500 non-null    str
 7   kualitas     500 non-null    str
dtypes: float64(4), str(4)
memory usage: 44.7 KB

In [6]:
df.describe()

         diameter       berat  tebal_kulit  kadar_gula
count  500.000000  500.000000   500.000000  500.000000
mean     6.514780  150.670600     0.730460   10.020200
std      0.955277   44.637103     0.252194    1.882291
min      3.990000   74.400000     0.270000    5.800000
25%      5.747500  106.000000     0.540000    8.600000
50%      6.540000  151.600000     0.690000   10.100000
75%      7.290000  188.050000     0.882500   11.500000
max      8.730000  277.100000     1.620000   14.600000

In [8]:
df['asal_daerah'].value_counts()

asal_daerah
Jawa Tengah    194
Kalimantan     163
Jawa Barat     143
Name: count, dtype: int64

In [9]:
df['warna'].value_counts()

warna
hijau     255
kuning    148
oranye     97
Name: count, dtype: int64